[package]
name = "time-zone-api"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.12.0"
lazy_static = "1.5.0"
serde_json = "1.0.118"

tokio = "1.38.0"
tower-http = { version = "0.5.2", features = ["cors"] }
tzf-rs = "0.4.8"
